### ISSUE TITLE
Component: Profile Setting Card

### ISSUE THREAD

**Issue by leedahw** [imm-suum/suum#17]
To be used in Settings Screen.
Display User name and info. 
Info should be editable (function can be added later)

Images:
![image](https://user-images.githubusercontent.com/71396271/109678484-aae61800-7b48-11eb-8ed1-ef5c57316abb.png)

Notes:
- Edit Button use Icon from FontAwesome
- Display Name and Email.

**Comment by thisisoke** [comment]
@scdoja  noticed you tagged this ticket as a bug. whats the issue?
